Multiple fixes detected by Valgrind: * Make sure to initialize all our structs to zero; some of these were harmless   but it's easier to troubleshoot later. * Fix a possible deadlock in fs_readdir() with parent/child dir lock order * Use malloc() instead of calloc() to avoid copy-on-write from the zero page;   not sure how this really affects performance but I think we have more control   over zeroing by simply doing a small bzero after malloc(), plus we're confident   we're going to write immediately after allocation. * Make sure we properly get the bytes_lock on oinode's everytime we want to stat. * Added some TODOs for initial troubleshooting of some other lock issues with   fs_rename

diff --git a/potatofs.init b/potatofs.init
--- a/potatofs.init
+++ b/potatofs.init
@@ -29,7 +29,7 @@ case $1 in
 		echo "OK."
 
 		echo -n "* fsck..."
-		$binpath/potatoctl -c $conf fsck quiet || exit 1
+		$binpath/potatoctl -c $conf fsck quiet || fatal "fsck had errors"
 		echo "OK."
 
 		echo "* Mounting..."
